spring:
  datasource:
    url: mongodb://localhost:27017/main

logging:
  level:
    org:
      flywaydb: debug

mongock:
#  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2